[theme]

# Primary accent for interactive elements
primaryColor = '#FF6969'

# Background color for the main content area
backgroundColor = '#F9F5E7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0EA293'

# Color used for almost all text
textColor = '#2F0F5D'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
