[theme]

# Primary accent for interactive elements
primaryColor = '#FF6969'

# Background color for the main content area
backgroundColor = '#39B5E0'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#F5EA5A'

# Color used for almost all text
textColor = '#2F58CD'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
